-- Migration: Add SEO history table to keep previous SEO properties per project
CREATE TABLE IF NOT EXISTS seo_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name TEXT NOT NULL,
    properties JSONB NOT NULL,
    saved_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS seo_history_project_name_idx ON seo_history (project_name);